version: "3"

services:
  testing_db:
    image: postgres:12.3
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: kyokdy_test
    ports:
      - 5433:5432
  db:
    image: postgres:12.3
    restart: always
    user: $UID:$GID
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: kyokdy
    ports:
      - 5432:5432
    volumes:
      - ./db_data:/var/lib/postgresql/data
  adminer:
    image: donnex/pgweb
    command: "-s --bind=0.0.0.0 --listen=8080 --url postgresql://root:root@db/kyokdy?sslmode=disable"
    links:
      - db:db
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
      - testing_db
  adminer-test:
    image: donnex/pgweb
    command: "-s --bind=0.0.0.0 --listen=8080 --url postgresql://root:root@testing_db/kyokdy_test?sslmode=disable"
    links:
      - db:db
    restart: always
    ports:
      - 8081:8080
    depends_on:
      - db
      - testing_db
